### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by happysmile111** [arpcard/FAQ#1]
how to solve the issue which is "the json file size greater than 20M ", thank you

**Comment by huynhw1** [comment]
Hello @happysmile111 ,

Please put any issue about CARD or RGI in the appropriate repositories. This is the FAQ.

But to answer your question. The 20Mb limit is what we have in the CARD RGI webtool. This is not an issue. Your json file is too large for our webtool to work with.

Thank you.

**Comment by happysmile111** [comment]
> Hello @happysmile111 ,
> Please put any issue about CARD or RGI in the appropriate repositories. This is the FAQ.
> But to answer your question. The 20Mb limit is what we have in the CARD RGI webtool. This is not an issue. Your json file is too large for our webtool to work with.
> Thank you.

thanks for your anwser, mybe the command-line tool can availvable when json file size greater than 20M or no limit ?

**Comment by huynhw1** [comment]
@happysmile111 

The command-line visualization is an ongoing project we have. Stay tuned for updates regarding that feature. Once it is implemented, you can visualize items that are greater than 20mb.

Do not ethat it is uncommon for JSONs to be greater than 20mb, so if my guess is correct, you are trying to visualize metagenomic data which our webtool does not support.

Thank you.
